version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0 # Dùng image có sẵn cho DB
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: eproject
    networks:
      - eproject-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management # Dùng image có sẵn cho broker
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - eproject-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build: ./auth # <-- Dùng 'build'
    container_name: auth-service
    environment:
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
      - MONGODB_AUTH_URI=mongodb://mongodb:27017/auth
    depends_on:
      mongodb:
        condition: service_healthy # Chờ DB sẵn sàng
    networks:
      - eproject-network

  # Product Service
  product-service:
    build: ./product # <-- Dùng 'build'
    container_name: product-service
    environment:
      - PORT=3001
      - JWT_SECRET=your_jwt_secret_key_here
      - MONGODB_PRODUCT_URI=mongodb://mongodb:27017/product
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672
      - QUEUE_NAME=products
      - ORDER_SERVICE_URL=http://order-service:3002
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - eproject-network

  # Order Service
  order-service:
    build: ./order # <-- Dùng 'build'
    container_name: order-service
    environment:
      - PORT=3002
      - JWT_SECRET=your_jwt_secret_key_here
      - MONGODB_ORDER_URI=mongodb://mongodb:27017/order
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq:5672
      - RABBITMQ_QUEUE=orders
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - eproject-network

  # API Gateway
  api-gateway:
    build: ./api-gateway # <-- Dùng 'build'
    container_name: api-gateway
    environment:
      - PORT=3003
      - AUTH_SERVICE_URL=http://auth-service:3000
      - PRODUCT_SERVICE_URL=http://product-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - eproject-network

  # E2E Tester Service
  e2e-tester:
    build: ./e2e-tests # <-- Dùng 'build'
    container_name: e2e-tester
    environment:
      - API_GATEWAY_URL=http://api-gateway:3003
    depends_on:
      - api-gateway
    networks:
      - eproject-network
    command: ["npm", "test"]

networks:
  eproject-network:
    driver: bridge

