# Sử dụng một image Node
FROM node:18-alpine

# Thư mục làm việc
WORKDIR /app

# Sao chép file package và cài đặt dependencies
COPY package*.json ./
RUN npm install

# Sao chép toàn bộ mã nguồn (chủ yếu là thư mục test)
COPY . .

# Lệnh này sẽ được chạy khi container khởi động
# Nó sẽ thực thi kịch bản test "scripts.test" trong file package.json
CMD [ "npm", "test" ]
